# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install Requirements for ${{ matrix.os }}
        run: sudo apt install gifsicle
        if: matrix.os  == 'ubuntu-latest'

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Add PyInstaller
        run: pip install -U pip wheel setuptools PyInstaller

      # Runs a single command using the runners shell
      - name: PIP requirements
        run: pip install -r requirements.txt

      - name: SDL WTF
        env:
          CC: gcc-9
          CXX: g++-9
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 9
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/gcc-9 9
          cd vendor
          bash build.sh
          cd ..
        if: matrix.os == 'ubuntu-latest'

      # Runs a set of commands using the runners shell
      - name: Build
        run: pyxelpackager main.py
        if: matrix.os == 'windows-latest'

      - name: Build Linux
        run: python build.py main.py
        if: matrix.os == 'ubuntu-latest'
      
      - name: Upload Linux Build
        uses: actions/upload-artifact@v2.2.1
        with:
          name: Linux-bin
          path: dist/main
        if: matrix.os == 'ubuntu-latest'

      - name: Upload Windows Build
        uses: actions/upload-artifact@v2.2.1
        with:
          name: W32-bin
          path: dist/main.exe
        if: matrix.os == 'windows-latest'
